// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Menuitem struct {
	ID           int32
	RestaurantID int32
	Name         string
	Price        float64
	Description  sql.NullString
	Available    sql.NullBool
}

type Order struct {
	ID           int32
	Customerid   int32
	Restaurantid int32
	Courierid    sql.NullInt32
	Status       string
	CreatedAt    sql.NullTime
}

type Orderitem struct {
	OrderID    int32
	MenuItemID int32
	Quanity    int32
}

type User struct {
	ID           int32
	Email        string
	HashPassword string
	UserRole     string
	CreatedAt    time.Time
	Phone        string
}
