// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(customerid, restaurantid, address, status, created_at)
VALUES (
        $1,
        $2,
        $3,
        'pending',
        NOW()
)
RETURNING id, customerid, restaurantid, courierid, status, created_at, address
`

type CreateOrderParams struct {
	Customerid   int32
	Restaurantid int32
	Address      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.Customerid, arg.Restaurantid, arg.Address)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Customerid,
		&i.Restaurantid,
		&i.Courierid,
		&i.Status,
		&i.CreatedAt,
		&i.Address,
	)
	return i, err
}

const getCurrentIDOrderForCourier = `-- name: GetCurrentIDOrderForCourier :one
SELECT id FROM orders
WHERE status = 'delivering' AND courierid=$1
`

func (q *Queries) GetCurrentIDOrderForCourier(ctx context.Context, courierid sql.NullInt32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCurrentIDOrderForCourier, courierid)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getCurrentOrderForCourier = `-- name: GetCurrentOrderForCourier :many
SELECT
    orders.id AS order_id,
    orders.status,
    orders.created_at,
    orders.address AS delivery_address,

    orderitem.menu_item_id,
    orderitem.quanity,

    menuitem.name AS menu_item_name,
    menuitem.price,

    restaurants.address AS restaurant_address,
    restaurants.user_name AS restaurant_name,
    restaurants.phone AS restaurant_phone,

    customer.phone AS customer_phone

FROM orders
         JOIN orderitem ON orders.id = orderitem.order_id
         JOIN menuitem ON orderitem.menu_item_id = menuitem.id
         JOIN users AS restaurants ON orders.restaurantid = restaurants.id
         JOIN users AS customer ON orders.customerid = customer.id
WHERE orders.status = 'delivering' AND orders.courierid = $1
`

type GetCurrentOrderForCourierRow struct {
	OrderID           int32
	Status            string
	CreatedAt         sql.NullTime
	DeliveryAddress   string
	MenuItemID        int32
	Quanity           int32
	MenuItemName      string
	Price             float64
	RestaurantAddress sql.NullString
	RestaurantName    sql.NullString
	RestaurantPhone   string
	CustomerPhone     string
}

func (q *Queries) GetCurrentOrderForCourier(ctx context.Context, courierid sql.NullInt32) ([]GetCurrentOrderForCourierRow, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentOrderForCourier, courierid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentOrderForCourierRow
	for rows.Next() {
		var i GetCurrentOrderForCourierRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Status,
			&i.CreatedAt,
			&i.DeliveryAddress,
			&i.MenuItemID,
			&i.Quanity,
			&i.MenuItemName,
			&i.Price,
			&i.RestaurantAddress,
			&i.RestaurantName,
			&i.RestaurantPhone,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFullOrderByID = `-- name: GetFullOrderByID :many
SELECT
    orders.id AS order_id,
    orders.status,
    orders.created_at,
    orders.address AS delivery_address,

    orderitem.menu_item_id,
    orderitem.quanity,

    menuitem.name AS menu_item_name,
    menuitem.price,

    restaurants.address AS restaurant_address,
    restaurants.user_name AS restaurant_name,
    restaurants.phone AS restaurant_phone,

    customer.user_name AS costomer_name,
    customer.phone AS customer_phone,
    customer.id AS customer_id,

    courier.user_name AS courier_name

FROM orders
         JOIN orderitem ON orders.id = orderitem.order_id
         JOIN menuitem ON orderitem.menu_item_id = menuitem.id
         JOIN users AS restaurants ON orders.restaurantid = restaurants.id
         JOIN users AS customer ON orders.customerid = customer.id
        LEFT JOIN users AS courier ON orders.courierid = courier.id
WHERE orders.id = $1
`

type GetFullOrderByIDRow struct {
	OrderID           int32
	Status            string
	CreatedAt         sql.NullTime
	DeliveryAddress   string
	MenuItemID        int32
	Quanity           int32
	MenuItemName      string
	Price             float64
	RestaurantAddress sql.NullString
	RestaurantName    sql.NullString
	RestaurantPhone   string
	CostomerName      sql.NullString
	CustomerPhone     string
	CustomerID        int32
	CourierName       sql.NullString
}

func (q *Queries) GetFullOrderByID(ctx context.Context, id int32) ([]GetFullOrderByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFullOrderByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullOrderByIDRow
	for rows.Next() {
		var i GetFullOrderByIDRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Status,
			&i.CreatedAt,
			&i.DeliveryAddress,
			&i.MenuItemID,
			&i.Quanity,
			&i.MenuItemName,
			&i.Price,
			&i.RestaurantAddress,
			&i.RestaurantName,
			&i.RestaurantPhone,
			&i.CostomerName,
			&i.CustomerPhone,
			&i.CustomerID,
			&i.CourierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFullOrdersByUserID = `-- name: GetFullOrdersByUserID :many
SELECT
    orders.id AS order_id,
    orders.status,
    orders.created_at,
    orders.address AS delivery_address,

    orderitem.menu_item_id,
    orderitem.quanity,

    menuitem.name AS menu_item_name,
    menuitem.price,

    restaurants.address AS restaurant_address,
    restaurants.user_name AS restaurant_name,
    restaurants.phone AS restaurant_phone,

    customer.user_name AS costomer_name,
    customer.phone AS customer_phone

FROM orders
         JOIN orderitem ON orders.id = orderitem.order_id
         JOIN menuitem ON orderitem.menu_item_id = menuitem.id
         JOIN users AS restaurants ON orders.restaurantid = restaurants.id
         JOIN users AS customer ON orders.customerid = customer.id
WHERE orders.customerid = $1
`

type GetFullOrdersByUserIDRow struct {
	OrderID           int32
	Status            string
	CreatedAt         sql.NullTime
	DeliveryAddress   string
	MenuItemID        int32
	Quanity           int32
	MenuItemName      string
	Price             float64
	RestaurantAddress sql.NullString
	RestaurantName    sql.NullString
	RestaurantPhone   string
	CostomerName      sql.NullString
	CustomerPhone     string
}

func (q *Queries) GetFullOrdersByUserID(ctx context.Context, customerid int32) ([]GetFullOrdersByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFullOrdersByUserID, customerid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullOrdersByUserIDRow
	for rows.Next() {
		var i GetFullOrdersByUserIDRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Status,
			&i.CreatedAt,
			&i.DeliveryAddress,
			&i.MenuItemID,
			&i.Quanity,
			&i.MenuItemName,
			&i.Price,
			&i.RestaurantAddress,
			&i.RestaurantName,
			&i.RestaurantPhone,
			&i.CostomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFullPendingOrders = `-- name: GetFullPendingOrders :many
SELECT
    orders.id AS order_id,
    orders.status,
    orders.created_at,
    orders.address AS delivery_address,

    orderitem.menu_item_id,
    orderitem.quanity,

    menuitem.name AS menu_item_name,
    menuitem.price,

    restaurants.address AS restaurant_address,
    restaurants.user_name AS restaurant_name,
    restaurants.phone AS restaurant_phone,

    customer.user_name AS costomer_name,
    customer.phone AS customer_phone

FROM orders
         JOIN orderitem ON orders.id = orderitem.order_id
         JOIN menuitem ON orderitem.menu_item_id = menuitem.id
         JOIN users AS restaurants ON orders.restaurantid = restaurants.id
        JOIN users AS customer ON orders.customerid = customer.id
WHERE orders.status = 'pending'
`

type GetFullPendingOrdersRow struct {
	OrderID           int32
	Status            string
	CreatedAt         sql.NullTime
	DeliveryAddress   string
	MenuItemID        int32
	Quanity           int32
	MenuItemName      string
	Price             float64
	RestaurantAddress sql.NullString
	RestaurantName    sql.NullString
	RestaurantPhone   string
	CostomerName      sql.NullString
	CustomerPhone     string
}

func (q *Queries) GetFullPendingOrders(ctx context.Context) ([]GetFullPendingOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFullPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullPendingOrdersRow
	for rows.Next() {
		var i GetFullPendingOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Status,
			&i.CreatedAt,
			&i.DeliveryAddress,
			&i.MenuItemID,
			&i.Quanity,
			&i.MenuItemName,
			&i.Price,
			&i.RestaurantAddress,
			&i.RestaurantName,
			&i.RestaurantPhone,
			&i.CostomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderStatusByID = `-- name: GetOrderStatusByID :one
SELECT orders.status FROM orders
WHERE orders.id = $1
`

func (q *Queries) GetOrderStatusByID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrderStatusByID, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updateCourierID = `-- name: UpdateCourierID :many
WITH updated_order AS (
    UPDATE orders
    SET courierid = $1,
        status = 'delivering'
    WHERE orders.id = $2
    RETURNING id, customerid, restaurantid, courierid, status, created_at, address
)
SELECT
    o.id AS order_id,
    o.status,
    o.created_at,
    o.address AS delivery_address,

    orderitem.menu_item_id,
    orderitem.quanity,

    menuitem.name AS menu_item_name,
    menuitem.price,

    restaurants.address AS restaurant_address,
    restaurants.user_name AS restaurant_name,
    restaurants.phone AS restaurant_phone,

    customer.user_name AS costomer_name,
    customer.phone AS customer_phone,
    customer.id AS customer_id,

    courier.user_name AS courier_name

FROM updated_order o
         JOIN orderitem ON o.id = orderitem.order_id
         JOIN menuitem ON orderitem.menu_item_id = menuitem.id
         JOIN users AS restaurants ON o.restaurantid = restaurants.id
         JOIN users AS customer ON o.customerid = customer.id
         LEFT JOIN users AS courier ON o.courierid = courier.id
`

type UpdateCourierIDParams struct {
	Courierid sql.NullInt32
	ID        int32
}

type UpdateCourierIDRow struct {
	OrderID           int32
	Status            string
	CreatedAt         sql.NullTime
	DeliveryAddress   string
	MenuItemID        int32
	Quanity           int32
	MenuItemName      string
	Price             float64
	RestaurantAddress sql.NullString
	RestaurantName    sql.NullString
	RestaurantPhone   string
	CostomerName      sql.NullString
	CustomerPhone     string
	CustomerID        int32
	CourierName       sql.NullString
}

func (q *Queries) UpdateCourierID(ctx context.Context, arg UpdateCourierIDParams) ([]UpdateCourierIDRow, error) {
	rows, err := q.db.QueryContext(ctx, updateCourierID, arg.Courierid, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateCourierIDRow
	for rows.Next() {
		var i UpdateCourierIDRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Status,
			&i.CreatedAt,
			&i.DeliveryAddress,
			&i.MenuItemID,
			&i.Quanity,
			&i.MenuItemName,
			&i.Price,
			&i.RestaurantAddress,
			&i.RestaurantName,
			&i.RestaurantPhone,
			&i.CostomerName,
			&i.CustomerPhone,
			&i.CustomerID,
			&i.CourierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET courierid = $1,
    status = 'delivered'
WHERE orders.id = $2
`

type UpdateOrderStatusParams struct {
	Courierid sql.NullInt32
	ID        int32
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Courierid, arg.ID)
	return err
}
