// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, hash_password, user_role, phone, created_at)
VALUES (
        $1,
        $2,
        $3,
        $4,
        NOW()
)
RETURNING id, email, hash_password, user_role, created_at, phone
`

type CreateUserParams struct {
	Email        string
	HashPassword string
	UserRole     string
	Phone        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.HashPassword,
		arg.UserRole,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashPassword,
		&i.UserRole,
		&i.CreatedAt,
		&i.Phone,
	)
	return i, err
}
