-- +goose Up

CREATE TABLE IF NOT EXISTS MenuItem (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id int NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price FLOAT NOT NULL,
    description TEXT,
    available BOOLEAN
);

-- +goose Down

DROP TABLE IF EXISTS MenuItem;