-- +goose Up
CREATE TABLE IF NOT EXISTS orders(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customerID int NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    restaurantID int NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    courierID int REFERENCES users (id),
    status TEXT NOT NULL,
    created_at TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS orders;